### ISSUE TITLE
MyAgro f2 & f3 job descriptions

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/core#50]
MyAgro's f2 job description (https://openfn-core.herokuapp.com/job_descriptions/4) is identical to their f3 (https://openfn-core.herokuapp.com/job_descriptions/5) except for slightly different destination fields. Both give the same error. The objectives are as follows:

Form 2: Update GPs, assigning them to a "Zone__c" via "Zone_Code__c", and giving them a "Sent_Timestamp__c".

Form 3: Update GPs, assigning them to a "BA__c" via "Badge_Code__c", and giving them a "Received_Timestamp__c".

Here is the Form 2 JD:
```
steps(
  each(
    upsert("Packet__c", "Grand_Packet_extID__c", fields(
      field("Grand_Packet_extID__c", sourceValue("$.data.form.ID_cards_send_to_zone")),
      field("Date_Received__c", sourceValue("$.data.form.meta.timeEnd")),
      lookup("Zone__r", "Zone_Code__c", "$.data.form.ID_zone_to_send_to"))
    )
  )
)
```
when processing a typical receipt
```
{
  version: "62",
  uiversion: "1",
  type: "data",
  resource_uri: "",
  received_on: "2015-12-22T11:34:28.029521",
  problem: null,
  metadata: {
    username: "demo_user",
    userID: "demo_user",
    timeStart: "2015-12-22T11:26:50.932000",
    timeEnd: "2015-12-22T11:27:12.275000",
    location: null,
    instanceID: "0d11cbaa-7469-4e96-a976-f952c7aeb860",
    doc_type: "Metadata",
    deviceID: "353507070278574",
    deprecatedID: null,
    appVersion: "CommCare Android, version "2.25.0"(410006). App v62. CommCare Version 2.25. Build 410006, built on: 2015-12-17"
  },
  md5: "OBSOLETED",
  is_phone_submission: "1.0",
  initial_processing_complete: true,
  id: "0d11cbaa-7469-4e96-a976-f952c7aeb860",
  form: {
    meta: {
      username: "demo_user",
      userID: "demo_user",
      timeStart: "2015-12-22T11:26:50.932000",
      timeEnd: "2015-12-22T11:27:12.275000",
      instanceID: "0d11cbaa-7469-4e96-a976-f952c7aeb860",
      deviceID: "353507070278574",
      appVersion: {
        "@xmlns": "http://commcarehq.org/xforms",
        "#text": "CommCare Android, version "2.25.0"(410006). App v62. CommCare Version 2.25. Build 410006, built on: 2015-12-17"
      },
      "@xmlns": "http://openrosa.org/jr/xforms"
    },
    ID_zone_to_send_to: "a2Fb00000005Twr",
    ID_cards_send_to_zone: "paquet 1503",
    "@xmlns": "http://openrosa.org/formdesigner/28206D23-CA96-4583-9C7D-D65FB08C6CC7",
    "@version": "62",
    "@uiVersion": "1",
    "@name": "2) Envoyez des cartes dans les zones",
    "#type": "data"
  },
  domain: "track-trace-vendor-card",
  build_id: "c0493acef06ec3c31c373e9403cce8c7",
  attachments: {
    "form.xml": {
      length: 866,
      content_type: "text/xml"
    }
  },
  archived: false,
  app_id: "2843e2999ca7a77f0f7b8cb7a3e8e3f9"
}
```
yields this error (https://openfn-core.herokuapp.com/submissions/601)
```
Logging in as myagro@vera.org.openfn.
Upserting Packet__c with externalId Grand_Packet_extID__c : { Grand_Packet_extID__c: 'paquet 1503',
  Date_Received__c: '2015-12-22T11:27:12.275000',
  Zone__r: { Zone_Code__c: 'a2Fb00000005Twr' } }
[TypeError: undefined is not a function]
TypeError: undefined is not a function
    at /app/node_modules/language-salesforce/lib/sourceHelpers.js:138:32
    at /app/node_modules/language-salesforce/node_modules/jsforce/node_modules/promise/lib/core.js:33:15
    at flush (/app/node_modules/language-salesforce/node_modules/jsforce/node_modules/promise/node_modules/asap/asap.js:27:13)
    at process._tickCallback (node.js:355:11)
Job failed.
```
It should upsert Packet__c with `Grand_Packet_extID__c` (extID), `Date_Received__c`, and `Zone__r` and as far as I can tell it's doing all of that. @stuartc , why is this sucker failing?

**Comment by stuartc** [comment]
Appears to be the same issue here: https://github.com/OpenFn/core/issues/51#issuecomment-169937800
