### ISSUE TITLE
edit form 1 JD for MyAgro

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/core#51]
This is a different problem, @stuartc : I'm not able to correctly access the repeat blocks and join in the parent information.

The objective is this: Form 1: Create new Package__c (GP), and update/upsert Small_Package__c (SP) records, linked to that GP.

form1 JD (https://openfn-core.herokuapp.com/job_descriptions/3):
```
steps(
  each(
    upsert("Packet__c", "Grand_Packet_extID__c", fields(
      field("name", sourceValue("$.data.form.ID_big_package")),
      field("Grand_Packet_extID__c", sourceValue("$.data.form.ID_big_package"))
    ))
  ),
  each(
    join("$.data.form.ID_cards_in_big_package[*]", "$.references[0].id", "Id"),
    upsert("Small_Packet__c", "sp_id__c", fields(
      field("Grand_Packet__c", sourceValue("$.data.Id")),
      field("sp_id__c", sourceValue("$.data.ID_cards_in_big_package"))
    ))
  )
)
```

form1 submission failure (https://openfn-core.herokuapp.com/submissions/609):
```
Logging in as myagro@vera.org.openfn.
Upserting Packet__c with externalId Grand_Packet_extID__c : { name: 'SMSTO:+22394806941:paquet 1399',
  Grand_Packet_extID__c: 'SMSTO:+22394806941:paquet 1399' }
[TypeError: undefined is not a function]
TypeError: undefined is not a function
    at /app/node_modules/language-salesforce/lib/sourceHelpers.js:138:32
    at /app/node_modules/language-salesforce/node_modules/jsforce/node_modules/promise/lib/core.js:33:15
    at flush (/app/node_modules/language-salesforce/node_modules/jsforce/node_modules/promise/node_modules/asap/asap.js:27:13)
    at process._tickCallback (node.js:355:11)
Job failed.
```

typical form1 receipt:
```
{
  version: "61",
  uiversion: "1",
  type: "data",
  resource_uri: "",
  received_on: "2016-01-04T11:41:55.884256",
  problem: null,
  metadata: {
    username: "adminbko",
    userID: "37955841cd916e425204256f0138be89",
    timeStart: "2016-01-04T11:03:01.314000",
    timeEnd: "2016-01-04T11:41:24.477000",
    location: null,
    instanceID: "781c2c8b-b833-42da-9727-f6e7acc766ce",
    doc_type: "Metadata",
    deviceID: "358111066290621",
    deprecatedID: null,
    appVersion: "CommCare Android, version "2.25.1"(410009). App v62. CommCare Version 2.25. Build 410009, built on: 2015-12-23"
  },
  md5: "OBSOLETED",
  is_phone_submission: "1.0",
  initial_processing_complete: true,
  id: "781c2c8b-b833-42da-9727-f6e7acc766ce",
  form: {
    meta: {
      username: "adminbko",
      userID: "37955841cd916e425204256f0138be89",
      timeStart: "2016-01-04T11:03:01.314000",
      timeEnd: "2016-01-04T11:41:24.477000",
      instanceID: "781c2c8b-b833-42da-9727-f6e7acc766ce",
      deviceID: "358111066290621",
      appVersion: {
        "@xmlns": "http://commcarehq.org/xforms",
        "#text": "CommCare Android, version "2.25.1"(410009). App v62. CommCare Version 2.25. Build 410009, built on: 2015-12-23"
      },
      "@xmlns": "http://openrosa.org/jr/xforms"
    },
    ID_cards_in_big_package: [
      {
        ID_cards_in_big_package: "Cards-500-347300-347349"
      },
      {
        ID_cards_in_big_package: "Cards-500-323650-323699"
      },
      {
        ID_cards_in_big_package: "Cards-500-347250-347299"
      },
      {
        ID_cards_in_big_package: "Cards-500-323700-323749"
      },
      {
        ID_cards_in_big_package: "Cards-1000-403650-403674"
      },
      {
        ID_cards_in_big_package: "Cards-1000-403625-403649"
      },
      {
        ID_cards_in_big_package: "Cards-1000-403600-403624"
      },
      {
        ID_cards_in_big_package: "Cards-2000-411870-411889"
      },
      {
        ID_cards_in_big_package: "Cards-2000-411850-411869"
      },
      {
        ID_cards_in_big_package: "smsto:94806941:5000-186750-186774"
      },
      {
        ID_cards_in_big_package: "smsto:94806941:8000-188825-188849"
      },
      {
        ID_cards_in_big_package: "smsto:948806941:10000-263800-263824"
      },
      {
        ID_cards_in_big_package: "Cards-25000-469050-469054"
      },
      {
        ID_cards_in_big_package: "Cards-500-323600-323649"
      },
      {
        ID_cards_in_big_package: "Cards-500-323550-323599"
      },
      {
        ID_cards_in_big_package: "Cards-500-323500-323549"
      },
      {
        ID_cards_in_big_package: "Cards-500-323450-323499"
      },
      {
        ID_cards_in_big_package: "Cards-1000-403725-403749"
      },
      {
        ID_cards_in_big_package: "Cards-1000-403700-403724"
      },
      {
        ID_cards_in_big_package: "Cards-1000-403675-403699"
      },
      {
        ID_cards_in_big_package: "Cards-2000-411810-411829"
      },
      {
        ID_cards_in_big_package: "Cards-2000-411830-411849"
      },
      {
        ID_cards_in_big_package: "smsto:94806941:5000-186100-186124"
      },
      {
        ID_cards_in_big_package: "smsto:94806941:8000-189750-189774"
      },
      {
        ID_cards_in_big_package: "smsto:94806941:10000-194650-194674"
      },
      {
        ID_cards_in_big_package: "Cards-25000-469045-469049"
      },
      {
        ID_cards_in_big_package: "Cards-500-323400-323449"
      },
      {
        ID_cards_in_big_package: "Cards-500-323350-323399"
      },
      {
        ID_cards_in_big_package: "Cards-500-323300-323349"
      },
      {
        ID_cards_in_big_package: "Cards-500-323250-323299"
      },
      {
        ID_cards_in_big_package: "Cards-1000-403025-403049"
      },
      {
        ID_cards_in_big_package: "Cards-1000-403050-403074"
      },
      {
        ID_cards_in_big_package: "Cards-1000-403075-403099"
      },
      {
        ID_cards_in_big_package: "Cards-2000-411790-411809"
      },
      {
        ID_cards_in_big_package: "Cards-2000-411770-411789"
      },
      {
        ID_cards_in_big_package: "smsto:948806941:5000-263500-263524"
      },
      {
        ID_cards_in_big_package: "smsto:94806941:8000-188900-188924"
      },
      {
        ID_cards_in_big_package: "smsto:94806941:10000-197800-197824"
      },
      {
        ID_cards_in_big_package: "Cards-25000-469040-469044"
      },
      {
        ID_cards_in_big_package: "Cards-500-322700-322749"
      },
      {
        ID_cards_in_big_package: "Cards-500-322600-322649"
      },
      {
        ID_cards_in_big_package: "Cards-500-322650-322699"
      },
      {
        ID_cards_in_big_package: "Cards-500-322550-322599"
      },
      {
        ID_cards_in_big_package: "Cards-1000-402950-402974"
      },
      {
        ID_cards_in_big_package: "Cards-1000-402975-402999"
      },
      {
        ID_cards_in_big_package: "Cards-1000-403000-403024"
      },
      {
        ID_cards_in_big_package: "Cards-2000-411750-411769"
      },
      {
        ID_cards_in_big_package: "Cards-2000-411730-411749"
      },
      {
        ID_cards_in_big_package: "smsto:948806941:5000-263575-263599"
      },
      {
        ID_cards_in_big_package: "smsto:94806941:8000-193700-193724"
      },
      {
        ID_cards_in_big_package: "smsto:948806941:10000-263825-263849"
      },
      {
        ID_cards_in_big_package: "Cards-25000-469035-469039"
      }
    ],
    ID_big_package: "SMSTO:+22394806941:paquet 1399",
    "@xmlns": "http://openrosa.org/formdesigner/F3783C32-4296-442F-ABF9-415BD3ED1DB3",
    "@version": "61",
    "@uiVersion": "1",
    "@name": "1) Creez grand paquet",
    "#type": "data"
  },
  domain: "track-trace-vendor-card",
  build_id: "c0493acef06ec3c31c373e9403cce8c7",
  attachments: {
    "form.xml": {
      length: 7478,
      content_type: "text/xml"
    }
  },
  archived: false,
  app_id: "2843e2999ca7a77f0f7b8cb7a3e8e3f9"
}
```

**Comment by taylordowns2000** [comment]
@stuartc , this stuff is live at beta.openfn.org

you can use your normal username and pass to see these records.

**Comment by stuartc** [comment]
The `each` operation expects a data source as it's first argument.

```js
steps(
  upsert("Packet__c", "Grand_Packet_extID__c", fields(
    field("name", sourceValue("$.data.form.ID_big_package")),
    field("Grand_Packet_extID__c", sourceValue("$.data.form.ID_big_package"))
  )),
  each(
    join("$.data.form.ID_cards_in_big_package[*]", "$.references[0].id", "Id"),
    upsert("Small_Packet__c", "sp_id__c", fields(
      field("Grand_Packet__c", sourceValue("$.data.Id")),
      field("sp_id__c", sourceValue("$.data.ID_cards_in_big_package"))
    ))
  )
)
```

Since there is only one `Packet_c` to upsert, you can remove the each operation, and just put an upsert operation right there. I haven't tested this with the production adaptor, but I did get the same error message with your example on the fake adaptor.
